name: Build and Release KOReader Plugin

on:
  push:
    branches:
      - master
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Prepare plugin folder
        run: |
          mkdir readingruler.koplugin
          shopt -s extglob
          cp -r !(readingruler.koplugin|.git|.github) readingruler.koplugin/

      - name: Create zip archive
        run: |
          zip -r readingruler.koplugin.zip readingruler.koplugin

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: readingruler.koplugin.zip
